server:
  port: 8080

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: member-service # ?? ??? ?
          uri: lb://member-service # member-service/application-dev.yml ? spring.application.name ? ??? ??? ??
          predicates:
            - Path=/member/** # ? ??? ???? ??? member-service? ??

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true # Zookeeper ? ??? ??? ??/??? ? ??, discovery.locator.enabled=true ? ???? ?? ???? ??
        register: true
        instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
